export const learningLessons = [
  {
    id: "spot-vs-perp",
    category: "交易基礎",
    title: "現貨 vs 合約",
    time: "3 min",
    summary: "現貨像是直接買入資產；合約則是用保證金控制更大的名目部位，盈虧與風險都會被放大。",
    points: ["現貨不會因槓桿被強平。", "合約可以做多也可以做空。", "合約倉位要先看保證金與強平估算。"],
    practiceLabel: "切到現貨看看",
  },
  {
    id: "order-types",
    category: "交易基礎",
    title: "市價單 vs 限價單",
    time: "4 min",
    summary: "市價單重視立即成交；限價單重視指定價格，但可能不會立刻成交。",
    points: ["市價單適合快速進出，但成交價可能滑動。", "限價單適合等待理想價格。", "下單前先看名目價值與手續費。"],
    practiceLabel: "練習限價單",
  },
  {
    id: "leverage-margin",
    category: "風險基礎",
    title: "槓桿與保證金",
    time: "5 min",
    summary: "槓桿不是增加勝率，而是放大部位。倍數越高，價格小幅波動對帳戶的影響越大。",
    points: ["保證金是開倉佔用資金。", "高槓桿需要更小倉位。", "先練習 5x、10x，再觀察 20x 的差異。"],
    practiceLabel: "觀察 20x 預覽",
  },
  {
    id: "pnl-drawdown",
    category: "績效基礎",
    title: "未實現 / 已實現損益",
    time: "4 min",
    summary: "未實現損益是尚未平倉的帳面變化；已實現損益是平倉後真正記入交易紀錄的結果。",
    points: ["單筆獲利不代表策略穩定。", "最大回撤能反映壓力與風險。", "ROI 要和交易次數、勝率一起看。"],
    practiceLabel: "查看績效區",
  },
  {
    id: "journal-emotion",
    category: "交易心理",
    title: "交易日誌與情緒",
    time: "5 min",
    summary: "交易日誌幫你看見自己是靠策略交易，還是被 FOMO、猶豫、報復性交易牽著走。",
    points: ["每筆交易都標記策略與情緒。", "評分不是看賺虧，而是看執行品質。", "一段時間後回看最容易虧錢的行為。"],
    practiceLabel: "打開日誌練習",
  },
];
